rvm:
  - 1.8.7
  # - 1.9.2
  # - 1.9.3
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=2.3.14
  - GEM=sunspot_rails RAILS=3.0.10
  - GEM=sunspot_rails RAILS=3.1.1

notifications:
  irc: "irc.freenode.org#sunspot-ruby"
  recipients:
    - alindeman@gmail.com

script:
  - ci/travis.sh
